from collections.abc import Callable
from pathlib import Path
from typing import Any, Protocol

from arwiz.foundation import InputSnapshot


class InputManagerProtocol(Protocol):
    def capture_input(self, function_name: str, args: tuple, kwargs: dict) -> InputSnapshot: ...
    def store_input(self, snapshot: InputSnapshot, base_path: Path | None = None) -> Path: ...
    def load_input(self, path: Path) -> InputSnapshot: ...
    def replay_input(self, snapshot: InputSnapshot, function: Callable) -> Any: ...
    def list_inputs(self, base_path: Path | None = None) -> list[InputSnapshot]: ...
